<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <!-- Ensure IDE/test tools recognize this as a test project -->
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <None Include=".github\workflows\dotnet-test.yml" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ApiForge\ApiForge.Api.csproj" />
    <ProjectReference Include="..\ApiForge.Generator\ApiForge.Generator.csproj" />
    <ProjectReference Include="..\ApiForge.Infrastructure\ApiForge.Infrastructure.csproj" />
    <ProjectReference Include="..\ApiForge.Application\ApiForge.ApplicationCore.csproj" />
    <ProjectReference Include="..\ApiForge.Domain\ApiForge.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="10.1.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Moq" Version="4.21.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <PackageReference Include="Microsoft.OpenApi" Version="3.10.2" />
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.5" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="10.0.12" />
  </ItemGroup>

</Project>
